apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: pihole
  name: pihole
spec:
  project: default
  destination: 
     namespace: pihole
     server: https://kubernetes.default.svc
  sources:
  - repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.34.0
    helm:
      valueFiles:
      - $values/k8s-apps/pihole/values.yaml
  - repoURL: https://github.com/momo-maurice/test.git
    ref: values