apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: "2.15.0"
      chart: pihole
      helm:
        releaseName: pihole
        valueFiles:
        - $values/k8s-apps/pihole/values.yaml
    - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: main
    ref: values
   syncPolicy:
    syncOptions:
      - CreateNamespace=true