apiVersion: v1
kind: Service
metadata:
  name: signal-service
  namespace: signal
spec:
  selector:
    app: signal
  #externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.7.119
  type: LoadBalancer
  ports:
    - name: signal
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal
  namespace: signal
  labels:
    app: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
        - name: signal
          image: bbernhard/signal-cli-rest-api:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MODE
            value: json-rpc
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/.local/share/signal-cli
              name: signal-volume
      volumes:
        - name:  signal-volume
          persistentVolumeClaim:
            claimName: signal-config-pvc
