apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    targetRevision: 2.35.0
    helm:
      parameters:
        - name: DNS1
          value: 192.168.7.1
    chart: pihole
    helm:
      releaseName: pihole
      valueFiles: 
        - $values/values.yaml
    repoURL: https://github.com/momo-maurice/test.git
    ref: values
    targetRevision: HEAD
    path: k8s-apps/pihole/
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true