apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  sources:
   -  repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.35.0
      chart: pihole
      helm:
        releaseName: pihole
        valueFiles: 
          - $values/pihole/values.yaml
    - repoURL: https://github.com/momo-maurice/test.git
      ref: values
      targetRevision: HEAD
      path: test/k8s-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true